# Generated by Django 5.0.4 on 2026-05-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(max_length=255),
        ),
    ]
